name: skana_ehentai

description: A flutter app for E-Hentai/EXHentai

publish_to: 'none'
version: 8.0.7+293

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # rewrite file mode
  dio:
    git:
      url: https://github.com/jiangtian616/dio
      path: dio
      ref: append-mode
  get: ^4.7.2
  get_storage: ^2.1.1
  extended_nested_scroll_view: ^6.2.1
  html: ^0.15.5+1
  logger: 2.2.0
  flutter_rating_bar: 4.0.1
  waterfall_flow: ^3.1.1
  extended_image: ^10.0.1
  font_awesome_flutter: ^10.8.0
  intl: 0.19.0
  collection: 1.19.0
  clipboard: 0.1.3
  scrollable_positioned_list: 
    git:
      url: https://github.com/jiangtian616/flutter.widgets
      path: packages/scrollable_positioned_list
  flutter_list_view: ^1.1.29
  executor: ^2.2.5
  retry: 3.1.2
  path: ^1.9.1
  drift: ^2.26.0
  sqlite3_flutter_libs: 0.5.32
  path_provider: ^2.1.5
  flutter_widget_from_html: ^0.16.0
  url_launcher: 6.3.1
  # add onLongPress
  like_button:
    git: https://github.com/jiangtian616/like_button
  webview_flutter: ^4.11.0
  desktop_webview_window:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins
      path: packages/desktop_webview_window
      ref: d0c91d9c3ea12883d38215adc48586753fb41dde
  # rewrite double tap & tap drag gesture
  photo_view:
    git:
      url: https://github.com/jiangtian616/photo_view
      ref: separate
  zoom_view: 
    git: https://github.com/jiangtian616/zoom_view
  package_info_plus: ^8.3.0
  file_picker: ^10.1.8
  local_auth: ^2.3.0
  blur: ^4.0.2
  flutter_windowmanager_plus: 1.0.1
  animate_do: ^4.2.0
  share_plus: ^11.0.0
  syncfusion_flutter_charts: ^29.1.39
  archive: ^4.0.7
  # https://github.com/ponnamkarthik/FlutterToast/pull/542
  fluttertoast: 
    git: 
      url: https://github.com/MarlonJD/FlutterToast
      ref: patch-1
  battery_plus: ^6.2.1
  throttling: ^2.0.1
  receive_sharing_intent: 
    git: https://github.com/KasemJaffer/receive_sharing_intent
  window_manager: ^0.4.3
  permission_handler: ^12.0.0+1
  grouped_list: ^6.0.0
  flutter_resizable_container: ^3.0.4
  simple_animations: ^5.1.0
  animated_flip_counter: ^0.3.4
  saver_gallery: ^3.0.6
  system_network_proxy: 
    git: 
      url: https://github.com/jiangtian616/system_network_proxy
      path: system_network_proxy
  http_proxy: 
    git: https://github.com/jiangtian616/http_proxy
  flutter_socks_proxy:
    # https://github.com/tayoji-io/socks_proxy/issues/7
    git: https://github.com/jiangtian616/socks_proxy
  flutter_draggable_gridview:
    # remove assert
    git:
      url: https://github.com/jiangtian616/flutter_draggable_gridview
  flutter_displaymode: 0.6.0
  pinput: ^5.0.1
  wakelock_plus: ^1.3.1
  flex_color_picker: ^3.7.0
  zoom_widget: 2.0.1
  android_intent_plus: 5.3.0
  integral_isolates: ^0.5.1
  screen_brightness: ^2.1.2
  crypto: ^3.0.6
  csv: ^6.0.0
  dotted_border: 2.1.0
  j_downloader:
    git: https://github.com/jiangtian616/JDownloader
  device_info_plus: ^11.4.0
  template_expressions: ^3.3.1+2
  uuid: 4.4.0
  xml: 6.5.0
  telegram: 0.0.9
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  moon_design: ^1.1.0
  bootstrap_icons: ^1.11.3
  custom_refresh_indicator: ^4.0.1
  calendar_date_picker2: ^2.0.0
  
dependency_overrides:
  test_api: 0.6.0
  matcher: 0.12.16
  chewie: 1.7.0
  http: 1.1.0
  cached_network_image: 3.3.0
  dio:
    git:
      url: https://github.com/jiangtian616/dio
      path: dio
      ref: append-mode
  collection: 1.19.0
  file_picker: 10.1.4
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  frontend_server_client: 4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true