#!/usr/bin/env sh
ln -sf /opt/skana_ehentai/skana_ehentai /usr/bin/skana_ehentai
chmod +x /usr/bin/skana_ehentai
update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
exit 0